services:
  test-pg-connector:
    container_name: test-pg-connector
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meroxauser
      POSTGRES_PASSWORD: meroxapass
      POSTGRES_DB: meroxadb
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "meroxadb", "-U", "meroxauser"]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - ./scripts:/scripts
      - "./docker-entrypoint-initdb.d/create_table_employees.sql:/docker-entrypoint-initdb.d/create_table_employees.sql"
    restart: unless-stopped
